FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    curl \
    git \
    make \
    nano \
    python3-pip \
    shellcheck

WORKDIR /app

COPY rename_files.sh /app/rename_files.sh

CMD ["/bin/bash"]
