name: Issue Template

description: Create a new issue
title: "[BUG/FEATURE/QUESTION]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      options:
        - Bug
        - Feature Request
        - Question
        - Documentation
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue
      placeholder: Describe the issue in detail...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: For bugs, please provide steps to reproduce the behavior
      placeholder: |
        1. Run the container with '...'
        2. Process files in '...'
        3. See error...
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Docker version: [e.g. 24.0.5]
        - Container version: [e.g. 1.1.0]
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contribution guidelines
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
