name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t checksum-file-renamer:test .
    
    - name: Run tests
      run: |
        mkdir -p test-data
        echo "Test file 1" > test-data/test1.txt
        echo "Test file 2" > test-data/test2.jpg
        
        docker run -v $(pwd)/test-data:/mounted_dir \
          -e INPUT_DIR=/mounted_dir \
          -e OUTPUT_DIR=/renamed_files \
          checksum-file-renamer:test
        
        # Check if the container ran successfully
        if [ $? -eq 0 ]; then
          echo "Test passed: Container ran successfully"
        else
          echo "Test failed: Container exited with error"
          exit 1
        fi
